/* we only selected relevant variable to speed up cleaning data process */

create table CovidDeaths (
iso_code varchar(255) not null,
continent varchar(255) default null,
location varchar(255) not null,
dates date not null,
population  bigint default null,
total_cases  bigint default null,
new_cases  bigint default null,
new_cases_smoothed double default  null, 
total_deaths  bigint default null,
new_deaths  bigint default null,
new_deaths_smoothed double default  null, 
total_cases_per_million double default  null, 
new_cases_per_million double default  null, 
new_cases_smoothed_per_million double default  null, 
total_deaths_per_million double default  null, 
new_deaths_per_million double default  null, 
new_deaths_smoothed_per_million double default  null, 
reproduction_rate double default  null, 
icu_patients  bigint default null,
icu_patients_per_million double default  null, 
hosp_patients  bigint default null,
hosp_patients_per_million double default  null, 
weekly_icu_admissions double default  null, 
weekly_icu_admissions_per_million double default  null, 
weekly_hosp_admissions double default  null, 
weekly_hosp_admissions_per_million double default  null);

-- original table 
/*
create table CovidDeaths (
iso_code varchar(255) not null,
continent varchar(255) default null,
location varchar(255) not null,
dates date not null,
population  bigint default null,
total_cases  bigint default null,
new_cases  bigint default null,
new_cases_smoothed double default  null, 
total_deaths  bigint default null,
new_deaths  bigint default null,
new_deaths_smoothed double default  null, 
total_cases_per_million double default  null, 
new_cases_per_million double default  null, 
new_cases_smoothed_per_million double default  null, 
total_deaths_per_million double default  null, 
new_deaths_per_million double default  null, 
new_deaths_smoothed_per_million double default  null, 
reproduction_rate double default  null, 
icu_patients  bigint default null,
icu_patients_per_million double default  null, 
hosp_patients  bigint default null,
hosp_patients_per_million double default  null, 
weekly_icu_admissions double default  null, 
weekly_icu_admissions_per_million double default  null, 
weekly_hosp_admissions double default  null, 
weekly_hosp_admissions_per_million double default  null);
*/